services:
  - type: web
    name: restaurant-yii2
    env: php
    plan: free
    region: frankfurt
    buildCommand: "composer install"
    startCommand: "php -S 0.0.0.0:10000 -t web"
    buildFilter:
      paths:
        - "*"
    autoDeploy: true